# Generated by Django 4.2.10 on 2024-03-03 02:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='dd', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
