# Generated by Django 4.2.10 on 2024-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR')], default='EUR', max_length=5),
            preserve_default=False,
        ),
    ]
